functionName: 'fcn.0066543b'
targetObjectPath: '/run/media/brunner56/MyBook/Workspaces/Mizuchi/target/swkotor-one-shot-source/function-reconstruction-tasks/0010_fcn_0066543b/target.bin'
asm: |
  fcn.0066543b:
      .byte 0x8e, 0xda, 0xed, 0x53, 0x07, 0x04, 0xb5, 0x26, 0xae, 0xac, 0xa8, 0x6f
      .byte 0x41, 0x2a, 0x67, 0x48, 0x11, 0x67, 0x18, 0xa2, 0xaa, 0x33, 0x5b, 0xac
      .byte 0x8e, 0x91, 0xaf, 0x5e, 0xa9, 0x0c, 0x1e, 0x58, 0xbf, 0x10, 0xc9, 0xe1
      .byte 0xc9, 0xa5, 0xba, 0xbc, 0xe0, 0x1f, 0x48, 0xc3
