#!/usr/bin/env python3
"""Generate and verify a byte-exact source roundtrip for one binary file."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def compiler_env() -> dict[str, str]:
    env = os.environ.copy()
    env.setdefault("CCACHE_DISABLE", "1")
    env.setdefault("CCACHE_DIR", str(ROOT / "target" / ".ccache"))
    return env


def run(args: list[str], timeout: int, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(args, cwd=cwd, text=True, capture_output=True, check=False, timeout=timeout, env=compiler_env())


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def asm_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def build_source(blob_ref: str, note: str) -> str:
    return "\n".join(
        [
            "/* Generated by binary-source-roundtrip.py. */",
            "/* Byte-source fallback: preserves exact original bytes, not semantic decompilation. */",
            f"/* {note} */",
            '.section .reconkit_image,"a"',
            ".global reconkit_full_binary_start",
            ".global reconkit_full_binary_end",
            "reconkit_full_binary_start:",
            f"  .incbin {asm_string(blob_ref)}",
            "reconkit_full_binary_end:",
            "",
        ]
    )


def verify_roundtrip(binary: Path, out_dir: Path, timeout: int, artifact_mode: str) -> dict[str, object]:
    out_dir.mkdir(parents=True, exist_ok=True)
    blob_path = out_dir / "original.bin" if artifact_mode == "full" else None
    source_path = out_dir / "full-binary.S"
    object_path = out_dir / "full-binary.o"
    rebuilt_path = out_dir / "rebuilt.bin"

    if blob_path is not None:
        shutil.copy2(binary, blob_path)
        source_path.write_text(build_source(blob_path.name, "Artifact mode: full; original bytes are copied beside this source."))
    else:
        source_path.write_text(
            build_source(
                str(binary.resolve()),
                "Artifact mode: lean; source references the installed original file to avoid retaining duplicate app data.",
            )
        )
    original_sha = sha256_file(binary)

    try:
        compile_proc = run(
            [
                "gcc",
                "-x",
                "assembler-with-cpp",
                "-c",
                source_path.name,
                "-o",
                object_path.name,
            ],
            timeout,
            cwd=out_dir,
        )
    except subprocess.TimeoutExpired:
        return {
            "schema": "reconkit.binary-source-roundtrip.v1",
            "binary": str(binary),
            "status": "failed",
            "byteIdentical": False,
            "error": f"assembler compile timed out after {timeout}s",
            "source": str(source_path),
            "blob": str(blob_path) if blob_path is not None else None,
            "artifactMode": artifact_mode,
        }

    objcopy_proc = subprocess.CompletedProcess(["objcopy"], 1, "", "compile failed")
    if compile_proc.returncode == 0:
        try:
            objcopy_proc = run(
                [
                    "objcopy",
                    "-O",
                    "binary",
                    "-j",
                    ".reconkit_image",
                    object_path.name,
                    rebuilt_path.name,
                ],
                timeout,
                cwd=out_dir,
            )
        except subprocess.TimeoutExpired:
            objcopy_proc = subprocess.CompletedProcess(["objcopy"], 124, "", f"objcopy timed out after {timeout}s")

    rebuilt_sha = sha256_file(rebuilt_path) if rebuilt_path.exists() else None
    rebuilt_size = rebuilt_path.stat().st_size if rebuilt_path.exists() else 0
    byte_identical = compile_proc.returncode == 0 and objcopy_proc.returncode == 0 and rebuilt_sha == original_sha
    object_retained = artifact_mode == "full"
    rebuilt_retained = artifact_mode == "full"
    if artifact_mode == "lean":
        for path in (object_path, rebuilt_path):
            try:
                path.unlink()
            except FileNotFoundError:
                pass
    report = {
        "schema": "reconkit.binary-source-roundtrip.v1",
        "binary": str(binary),
        "status": "matched" if byte_identical else "failed",
        "byteIdentical": byte_identical,
        "source": str(source_path),
        "blob": str(blob_path) if blob_path is not None else None,
        "object": str(object_path) if object_retained else None,
        "rebuiltBinary": str(rebuilt_path) if rebuilt_retained else None,
        "artifactMode": artifact_mode,
        "objectRetained": object_retained,
        "rebuiltBinaryRetained": rebuilt_retained,
        "originalSha256": original_sha,
        "rebuiltSha256": rebuilt_sha,
        "originalSize": binary.stat().st_size,
        "rebuiltSize": rebuilt_size,
        "compileReturnCode": compile_proc.returncode,
        "compileStdout": compile_proc.stdout[-4000:],
        "compileStderr": compile_proc.stderr[-4000:],
        "objcopyReturnCode": objcopy_proc.returncode,
        "objcopyStdout": objcopy_proc.stdout[-4000:],
        "objcopyStderr": objcopy_proc.stderr[-4000:],
        "strategy": "byte-source-incbin",
        "sourceType": "byte-source",
        "sourceAuthority": "original-bytes",
        "semanticDecompilation": False,
        "scopeNote": (
            "Whole-file bytes are reproduced from an included original byte blob; semantic decompilation coverage is tracked separately."
            if artifact_mode == "full"
            else "Whole-file bytes are reproduced from generated assembler source that references the installed original file; bulky object/rebuilt artifacts are not retained. Semantic decompilation coverage is tracked separately."
        ),
    }
    (out_dir / "binary-source-roundtrip.json").write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")
    return report


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--timeout", type=int, default=60)
    parser.add_argument(
        "--artifact-mode",
        choices=["full", "lean"],
        default="full",
        help="full retains copied blob/object/rebuilt files; lean verifies then retains only compact source/report artifacts.",
    )
    args = parser.parse_args()

    report = verify_roundtrip(args.binary, args.out, args.timeout, args.artifact_mode)
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if report["byteIdentical"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
