functionName: 'fcn.0055e215'
targetObjectPath: '/run/media/brunner56/MyBook/Workspaces/ReconstructKit/target/swkotor-one-shot-source/function-reconstruction-tasks/0016_fcn_0055e215/target.bin'
asm: |
  fcn.0055e215:
      .byte 0xa6, 0xf1, 0xec, 0x06, 0x8c, 0xaf, 0x18, 0x11, 0x8f, 0x8d, 0x67, 0x7b
      .byte 0xa7, 0xe8, 0xdb, 0xa1, 0x27, 0xa2, 0x1e, 0xef, 0x12, 0x56, 0x88, 0x3d
      .byte 0xd8, 0x00, 0x93, 0x43, 0x12, 0xa7, 0xae, 0x51, 0x4a, 0x4a, 0x93, 0xf0
      .byte 0xb2, 0xc2, 0xbd, 0x61, 0x45, 0x19, 0x5d, 0x20, 0x8f, 0xd3, 0x11, 0x24
      .byte 0x68, 0xda
