functionName: 'fcn.006cc8b9'
targetObjectPath: '/run/media/brunner56/MyBook/Workspaces/ReconstructKit/target/swkotor-one-shot-source/function-reconstruction-tasks/0020_fcn_006cc8b9/target.bin'
asm: |
  fcn.006cc8b9:
      .byte 0x43, 0x16, 0x8e, 0x9f, 0x71, 0xe7, 0x11, 0x2a, 0x40, 0x66, 0x1d, 0xfd
      .byte 0x0b, 0x61, 0xe8, 0x9d, 0x1f, 0xdd, 0x63, 0x5f, 0x19, 0x38, 0xdc, 0xb6
      .byte 0x72, 0x4c, 0x22, 0x2d, 0x25, 0x28, 0x63, 0x55, 0xa6, 0x8f
