functionName: 'fcn.00576147'
targetObjectPath: '/run/media/brunner56/MyBook/Workspaces/Mizuchi/target/swkotor-one-shot-source/function-reconstruction-tasks/0019_fcn_00576147/target.bin'
asm: |
  fcn.00576147:
      .byte 0x57, 0x24, 0x0f, 0x35, 0x6c, 0x88, 0xd7, 0xb1, 0xe6, 0xb3, 0xda, 0x65
      .byte 0xa1, 0xb6, 0x5b, 0x37, 0x3f, 0xd8, 0xad, 0x2a, 0x0a, 0x0a, 0x2f, 0x75
      .byte 0x00, 0x13, 0x5f, 0xdc, 0xd4, 0x3f, 0xea, 0x24, 0x65, 0x67, 0xb6, 0xc5
      .byte 0x60
