functionName: 'fcn.0070fc1c'
targetObjectPath: '/run/media/brunner56/MyBook/Workspaces/Mizuchi/target/swkotor-one-shot-source/function-reconstruction-tasks/0035_fcn_0070fc1c/target.bin'
asm: |
  fcn.0070fc1c:
      .byte 0x22, 0xea, 0xf1, 0x72, 0x30, 0x02, 0xfb, 0x33, 0x2d, 0x45, 0x01, 0x07
      .byte 0xb1, 0x72, 0x04, 0x20, 0xfb, 0x35, 0xf2, 0x6d, 0x51, 0x0a, 0x56, 0x8f
      .byte 0x90, 0x45, 0x74, 0x80, 0xc3, 0xfd, 0x4d, 0x6f, 0xc2, 0xd4, 0x38, 0xc3
      .byte 0x01, 0x10, 0x10, 0xbb, 0x8e, 0xd7, 0xec, 0x5e, 0x02, 0xe5, 0x1b
